---
os: linux
language: python
python:
- "2.7"
- "3.4"
- "3.5"
- "3.7"

jobs:
  fast_finish: true
  allow_failures:
  - python: "3.4"
  - python: "3.5"
  - python: "3.7"

env:
- PIPENV_VERBOSITY=-1

install:
- pip install --upgrade pipenv
- pipenv install --dev

script:
- pylint bme280
- pytest
